### ISSUE TITLE
Insert in EditV1 is not compatible with EditV2

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/open-scd-core#18]
I have discovered what I think is an unintentional breaking API change while testing the pre-release of the new open-scd-core.

The [Rename IEDs](https://github.com/danyill/oscd-rename-ieds) plugin I have created calls the `updateIED` function in scl-lib, which among other things updates the `textContent` of the `IEDName` and LGOS and LSVS `Val` elements for the supervision.

It does this with a Remove edit, removing the `Val` or `IEDName` elements and then recreating the `textContent`.

In our new core, we are not recognising the recreation of the `textContent` as an Insert edit because there is no `reference` parameter (obviously in future we will use the new SetTextContent edit type in preference but I expected us to be backwards compatible here).

In `handleEdit` we examined our EditV2 to see how best to use it:

```js
/** Applies an EditV2, returning the corresponding "undo" EditV2. */
export function handleEdit(edit: EditV2): EditV2 {
  if (isInsert(edit)) return handleInsert(edit);
  if (isRemove(edit)) return handleRemove(edit);
  if (isSetAttributes(edit)) return handleSetAttributes(edit);
  if (isSetTextContent(edit)) return handleSetTextContent(edit);
  if (isComplex(edit)) return edit.map((edit) => handleEdit(edit)).reverse();

  return [];
}
```

However the following edit is not any type and therefore is not processed.

```
> edit
{parent: Val, node: text}
> edit.parent
<Val>​</Val>​
> edit.node
"Test999CB/LLN0.Ind_1"
> isInsert(edit)
false
> isRemove(edit)
false
> isSetAttributes(edit)
false
> isSetTextContent(edit)
false
> isComplex(edit)
false
```

This should be recognised as an Insert edit (in the EditV1 API) but is not because it lacks a `reference`. 

Currently we have:

```
export function isInsert(edit: EditV2): edit is Insert {
  return (
    (edit as Insert).parent !== undefined &&
    (edit as Insert).node !== undefined &&
    (edit as Insert).reference !== undefined
  );
}
```

And `reference` is undefined.

It seems to me that we need a `convertInsert` function as part of `convertEdit` in `@OpenEnergyTools/xml-lib` to do this where reference is changed to `null` (somewhere in here https://github.com/OpenEnergyTools/xml-lib/blob/main/convertEdit.ts#L34).

Alternatively if `null` is not (or should not?) be a mandatory parameter in our new API for an Insert edit we would need to make a small modification to our new API (see https://github.com/OpenEnergyTools/open-scd-core/blob/main/API.md#edit-type).

**Comment by danyill** [comment]
Previously (and I'm not sure why) we had a much looser definition around `isInsert`:

https://github.com/OMICRONEnergy/open-scd-core/blob/9415e68269d07dcbd7b566b8ffa49894bc3b70a6/foundation/edit-event.ts#L31C1-L33C2

```js
export function isInsert(edit: Edit): edit is Insert {
  return (edit as Insert).parent !== undefined;
}
```

**Comment by danyill** [comment]
Arguably this could just be a bug in scl-lib where we have allowed the flexibility of Typescript semantics to ignore perhaps the intention of the typing:

https://github.com/OpenEnergyTools/scl-lib/blob/78e2e2f34fe53405485637a1ea36a01c4db323b3/tIED/updateIED.ts#L130-L134

IIUC then this:

```ts
export type Insert = {
  parent: Node;
  node: Node;
  reference: Node | null;
};
```

is equivalent to:

```ts
export type Insert = {
  parent: Node;
  node: Node;
  reference: Node | null | undefined
};
```

Which allows therefore:

```ts
export type Insert = {
  parent: Node;
  node: Node;
};
```

Which our new API does not allow - I think we should have a type guard or some kind of explicit requirement for reference and that we should provide backward compatibility by adding reference if it is missing on a `convertInsert` function but up for debate!

**Comment by JakobVogelsang** [comment]
It is a bug in the scl-lib. Insert has not been changed from edit v1 to edit v2. reference is a mendatory key since edit v1. It is so on purpose, because open-scd-core is a XML Editor and not a scl Editor ar least as a Concept.

**Comment by JakobVogelsang** [comment]
There is a fix for it now. I seriously don't know why type check has not worked on this oen, because the `Insert` type is clearly `..., reference: string | null`. I also have seen that the `updateIED` function has returns a wrong thing which is `Edit [] []`  instead of. `Edit[][]`. Are you sure this function has ever worked properly?

I would like to add regression tests to avoid in the future. Maybe you have a good idea?

**Comment by danyill** [comment]
> It is a bug in the scl-lib. Insert has not been changed from edit v1 to edit v2. reference is a mendatory key since edit v1. It is so on purpose, because open-scd-core is a XML Editor and not a scl Editor ar least as a Concept.

I guess that's fair. If the API was used incorrectly to begin with then it's not a bug as such.

I am quite uncomfortable though with the silent failure.
Do you think handleEdit should do something like this?

```ts
throw new Error(`Invalid edit provided: ${edit}`);
```

This is quite common in the type guard examples in typescript handbook.

Or perhaps:

```ts
console.error(`Invalid edit provided: ${edit}`)
```

It seems there is no easy way in Typescript because we use a union type to have `Edit[]` or `(Insert|Remove)[]` ensure that `reference` is defined. I thought `strictNullChecks` might help but it does not seem to.

If a variable had been used in our code for each array element it would have been noticed but that seems a bit OTT.

**Comment by JakobVogelsang** [comment]
Let's do that!

**Comment by danyill** [comment]
> Are you sure this function has ever worked properly?

Yip, I have used it squillions of times :wink:

**Comment by JakobVogelsang** [comment]
I would rather do `console.error(`Invalid edit provided: ${edit}`);`. What you say?

**Comment by danyill** [comment]
> I would rather do `console.error(`Invalid edit provided: ${edit}`);`. What you say?

For me this is OK and perhaps a good first step.

However the console error may not be visible to the user and in the case a plugin has provided instructions to make a change to a document which are just not valid it's highly likely that this will impact on the outcome the user is expecting. 

Shouldn't they somehow be made aware of this e.g. in the log?
